### ISSUE TITLE
point-click: Issue with grid display

### ISSUE THREAD

**Issue by arosich** [bjpirt/apps.mirobot.io#3]
The label "100mm grid" suggests there should be a grid show.
However, the grid appears only if I click "Reset" while the pointer is in motion.
Upon subsequent click on Reset the grid disappears. 

Chromium Version 39.0.2171.65 Built on Ubuntu 14.04, running on LinuxMint 17 (64-bit)

**Comment by bjpirt** [comment]
I can reproduce this - should be an easy fix I think.

**Comment by bjpirt** [comment]
I may also make the grid a bit darker while I'm at it :-)

**Comment by bjpirt** [comment]
2c472f28 fixes the black grid and 744bb98b makes the grid a little darker
